### ISSUE TITLE
fetch_data() throws exception "pymyenergi.exceptions.WrongCredentials" when password and email are correct 

### ISSUE THREAD

**Issue by Hanzanka** [CJNE/pymyenergi#21]
When running your example script with my password and username it throws en exception WrongCredentials. This also happens with the cli.

**Comment by G6EJD** [comment]
Are you using an API obtained from the ME web portal?

**Comment by Hanzanka** [comment]
I wasn't. But now I got the api keys for both, zappi and the hub, but I still hasn't get it to work.

**Comment by G6EJD** [comment]
Then your username is incorrect

**Comment by Hanzanka** [comment]
I didn't realise I have to use hub's SN as username, so I got it working now...

**Comment by G6EJD** [comment]
You can close this now!
