### ISSUE TITLE
Zappi, ECO+ phase setting

### ISSUE THREAD

**Issue by jwillemsen** [CJNE/pymyenergi#28]
Just upgraded to the latest zappi app (see https://myenergi.info/app-update-3-3-1-t12674.html#p122029) and this now has the option to set the phases to load in ECO+ mode, for this `phaseSetting` is used, when I change the setting in the app the diagnostics I can download in HA shows the following values:

```
"phaseSetting": "SINGLE_PHASE",

"phaseSetting": "THREE_PHASE",

"phaseSetting": "AUTO",
```

It looks my PR for using this as number of phases as part of https://github.com/CJNE/pymyenergi/pull/25 is not correct, it should return values 1, 3 or auto.

**Comment by jwillemsen** [comment]
Any ideas how we could set the phase setting from HA to myenergi, would love to set the phase setting to single or three phase based on power produced by my solar panels through HA, looking at the code we need some `cgi-set-*` call

**Comment by jwillemsen** [comment]
Asked on the forum, see https://myenergi.info/viewtopic.php?f=54&t=12847&from_new_topic=1

**Comment by d-hz** [comment]
> Any ideas how we could set the phase setting from HA to myenergi, would love to set the phase setting to single or three phase based on power produced by my solar panels through HA, looking at the code we need some `cgi-set-*` call

I've tried to figure out the relevant HTTP Endpoints, if I am correct it seems to be:

3 Phase
`cgi-zappi-phase-setting-{ZXXXXXXXX}>-1`

1 Phase 
`cgi-zappi-phase-setting-{ZXXXXXXXX}-0`

Auto
`cgi-zappi-phase-setting-{ZXXXXXXXX}-2`


`{ZXXXXXXXX}>` is the Serial Number of the Zappi and needs to replaced in the calls

I am getting the following Response:

`{
    "status": "0",
    "statustext": ""
}`

Maybe this helps?

**Comment by jwillemsen** [comment]
Is the > for three phase correct? This helps, will try to implement this next week

**Comment by d-hz** [comment]
> Is the > for three phase correct? This helps, will try to implement this next week

That was a typo. I have edited it. The schema seems to be the same for all three.
I was not able to test it in code (I have recorded the network traffic from the app and tried to check which query was made when selecting the option), maybe you can verify my results.

**Comment by jwillemsen** [comment]
Thanks, will try to implement this asap, I really can use it as a workaround for the problems I have

**Comment by jwillemsen** [comment]
Yes, this works, great! I have updated PR #28 to also provide the feature to set the phase setting
