### ISSUE TITLE
Accuracy of ct clamp figures

### ISSUE THREAD

**Issue by jmrush97** [CJNE/pymyenergi#3]
The ct clamp figures not be converted correctly. For example:
CT 1 Internal Load 0W
CT 2 Grid 122W
CT 3 Generation -25W
CT 4 None 0W
CT 5 None 0W
CT 6 None 0W

Supply voltage: 231.3V frequency: 49.94Hz
Power:
  Grid      : 115W
  Generated : -25W

at that time the generation figure was 2.5kw, house consumtiption was 2.5kw and grid 0.1kw.

**Comment by CJNE** [comment]
Re-open if still an issue, probably just misconfigured though?
